Inventory/urls.py
from django.contrib.auth import views as auth_views
from django.urls import reverse
from django.conf.urls import url
from .views import *
from Inventory import views
from .views import index
from Inventory.views import SearchResultsView
from django.urls import path


app_name = "Inventory"

urlpatterns =[

    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name= 'logout'),
    path('register/', views.register_request, name="register"),
    path('SearchResultsView', SearchResultsView.as_view(), name='search_results'),    

    #url(r'Login/$', auth_views.LoginView.as_view(template_name="templates/registration/login.html"),name="login"),
    #url(r'Logout/$', auth_views.LogoutView.as_view(),name="logout"),
    #url(r'SignUp/$', views.SignUp.as_view(template_name = "templates/registration/signup.html"),name="signup"),

    url(r"^$", index, name="index"),
    url(r"^contenu$", contenu, name="contenu"),

    #url(r"^$", WelcomePage.as_view(template_name = "Welcome_Page.html"), name="welcomepage"),
    #path("", WelcomePage.as_view(template_name = "Welcome_Page.html"), name="welcomepage"),


    url(r"^display_Rocky_Railway$", display_Rocky_Railway, name='display_Rocky_Railway'),
    url(r"^display_Roar$", display_Roar, name='display_Roar'),
    url(r"^display_Shipwreched$", display_Shipwreched, name='display_Shipwreched'),
    url(r"^display_FWN1$", display_FWN1, name='display_FWN1'),
    url(r"^display_FWN2$", display_FWN2, name='display_FWN2'),
    url(r"^display_FWN3$", display_FWN3, name='display_FWN3'),
    url(r"^display_LIFE_OF_JESUS$", display_LIFE_OF_JESUS, name='display_LIFE_OF_JESUS'),
    url(r"^display_Friends_with_God_Bible_Story$", display_Friends_with_God_Bible_Story, name='display_Friends_with_God_Bible_Story'),

    url(r"^add_Rocky_Railway$", add_Rocky_Railway, name='add_Rocky_Railway'),
    url(r"^add_Roar$", add_Roar, name='add_Roar'),
    url(r"^add_Shipwreched$", add_Shipwreched, name='add_Shipwreched'),
    url(r"^add_FWN1$", add_FWN1, name='add_FWN1'),
    url(r"^add_FWN2$", add_FWN2, name='add_FWN2'),
    url(r"^add_FWN3$", add_FWN3, name='add_FWN3'),
    url(r"^add_LIFE_OF_JESUS$", add_LIFE_OF_JESUS, name='add_LIFE_OF_JESUS'),
    url(r"^add_Friends_with_God_Bible_Story$", add_Friends_with_God_Bible_Story, name='add_Friends_with_God_Bible_Story'),

    url(r"^edit_Rocky_Railway/(?P<pk>\d+)$", edit_Rocky_Railway, name='edit_Rocky_Railway'),
    url(r"^edit_Roar/(?P<pk>\d+)$", edit_Roar, name='edit_Roar'),
    url(r"^edit_Shipwreched/(?P<pk>\d+)$", edit_Shipwreched, name='edit_Shipwreched'),
    url(r"^edit_FWN1/(?P<pk>\d+)$", edit_FWN1, name='edit_FWN1'),
    url(r"^edit_FWN2/(?P<pk>\d+)$", edit_FWN2, name='edit_FWN2'),
    url(r"^edit_FWN3/(?P<pk>\d+)$", edit_FWN3, name='edit_FWN3'),
    url(r"^edit_LIFE_OF_JESUS/(?P<pk>\d+)$", edit_LIFE_OF_JESUS, name='edit_LIFE_OF_JESUS'),
    url(r"^edit_Friends_with_God_Bible_Story/(?P<pk>\d+)$", edit_Friends_with_God_Bible_Story, name='edit_Friends_with_God_Bible_Story'),

    url(r"^delete_Rocky_Railway/(?P<pk>\d+)$", delete_Rocky_Railway, name='delete_Rocky_Railway'),
    url(r"^delete_Roar/(?P<pk>\d+)$", delete_Roar, name='delete_Roar'),
    url(r"^delete_Shipwreched/(?P<pk>\d+)$", delete_Shipwreched, name='delete_Shipwreched'),
    url(r"^delete_FWN1/(?P<pk>\d+)$", delete_FWN1, name='delete_FWN1'),
    url(r"^delete_FWN2/(?P<pk>\d+)$", delete_FWN2, name='delete_FWN2'),
    url(r"^delete_FWN3/(?P<pk>\d+)$", delete_FWN3, name='delete_FWN3'),
    url(r"^delete_LIFE_OF_JESUS/(?P<pk>\d+)$", delete_LIFE_OF_JESUS, name='delete_LIFE_OF_JESUS'),
    url(r"^delete_Friends_with_God_Bible_Story/(?P<pk>\d+)$", delete_Friends_with_God_Bible_Story, name='delete_Friends_with_God_Bible_Story'),
]

grouppublishingindia/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from Inventory import views
from django.conf.urls.static import static
from django.urls import reverse_lazy
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("Inventory.urls")),
    url('Inventory/',include('django.contrib.auth.urls')),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html',
          success_url=reverse_lazy('password_reset_done')),name="reset_password"
         ),

    path('password_reset/done/',
          auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name="password_reset_done"
         ),

    path('password_reset_confirm/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
          name="password_reset_confirm"
         ),

    path('reset_password_complete/',
          auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
          name="password_reset_complete"
         ),

    url(r'media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'media/(?P<path>.*)$', serve,{'document_root':settings.STATIC_ROOT}),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Inventory/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render,redirect,get_object_or_404
from .models import *


#class UserCreateForm(UserCreationForm):
    #class Meta:
        #fields = ("username","email","password1","password2")
        #model = get_user_model()

    #def __init__(self, *args, **kwargs):
        #super().__init__(*args, **kwargs)
        #self.fields["username"].label = "Display name"
        #self.fields["email"].label = "Email address"

#Create your forms here

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	def clean_email(self):
		if User.objects.filter(email=self.cleaned_data['email']).exists():
			raise forms.ValidationError("the given email is already registered")
		return self.cleaned_data['email']

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	#def save(self, commit=True):
		#user = super(NewUserForm, self).save(commit=False)
		#user.email = self.cleaned_data['email']
		#if commit:
			#user.save()
		#return user



class ProductForm(forms.ModelForm):
    Total_Produced = forms.CharField()
    def get_Total_Produced(self, obj):
        return obj.get_tottal_produced()

    class Meta:
        model = Product
        fields = ("Product","Total_Produced","Sales","Category")


class Rocky_RailwayForm(forms.ModelForm):
    class Meta:
        model = Rocky_Railway
        fields = ("Product","Total_Produced","Sales")

class RoarForm(forms.ModelForm):
    class Meta:
        model = Roar
        fields = ("Product","Total_Produced","Sales")

class ShipwrechedForm(forms.ModelForm):
    class Meta:
        model = Shipwreched
        fields = ("Product","Total_Produced","Sales")

class FWN1Form(forms.ModelForm):
    class Meta:
        model = FWN1
        fields = ("Product","Total_Produced","Sales")

class FWN2Form(forms.ModelForm):
    class Meta:
        model = FWN2
        fields = ("Product","Total_Produced","Sales")

class FWN3Form(forms.ModelForm):
    class Meta:
        model = FWN3
        fields = ("Product","Total_Produced","Sales")

class LIFE_OF_JESUSForm(forms.ModelForm):
    class Meta:
        model = LIFE_OF_JESUS
        fields = ("Product","Total_Produced","Sales")

class Friends_with_God_Bible_StoryForm(forms.ModelForm):
    class Meta:
        model = Friends_with_God_Bible_Story
        fields = ("Product","Total_Produced","Sales")

Inventory/views.py
from django.contrib.auth.models import User
from django.views import View
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
from Inventory import forms
from django.db.models import Q
from django.views.generic import TemplateView, ListView
from .forms import NewUserForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
#####################
from urllib.parse import urlparse, urlunparse

from django.conf import settings
# Avoid shadowing the login() and logout() views below.
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect, QueryDict
from django.shortcuts import resolve_url
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.http import (
    url_has_allowed_host_and_scheme, urlsafe_base64_decode,
)
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
##################
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.core.mail import EmailMultiAlternatives
from django import template
from django.contrib import messages #import messages
from email.message import EmailMessage
###################

# Create your views here.

#Index
def index(request):
    count = User.objects.count()
    return render(request,'index.html', {
        'count':count
    })

def contenu(request):
    return render(request,'contenu.html')


def password_reset(request):
	if request.method == "POST":
		form = PasswordReset(request.POST)
		if form.is_valid():
			data = form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=data)|Q(username=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"
					htmltemp = template.loader.get_template('password_reset_email.html')
					c = {
					"email":user.email,
					'domain':'127.0.0.1:8000',
					'site_name': 'Website',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)).decode(),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
					html_content = htmltemp.render(c)
					try:
						msg = EmailMultiAlternatives(subject, text_content, 'basaturninleo@gmail.com', [email])
						msg.attach_alternative(html_content, "text/html")
						msg.send()
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
					messages.info(request, "Password reset instructions have been sent to the email address entered.")
					return redirect ("index")
	form = PasswordReset()
	return render(request=request, template_name="password_reset_email.html", context={"form":form})







#Register(signup)
def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            #login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("Inventory:index")
        else:
            password1 = form.data['password1']
            password2 = form.data['password2']
            email = form.data['email']
            for msg in form.errors.as_data():
                if msg == 'email':
                    messages.error(request, f"Declared {email} is not valid")
                if msg == 'password2' and password1 == password2:
                    messages.error(request, f"Selected password: {password1} is not strong enough")
                elif msg == 'password2' and password1 != password2:
                    messages.error(request, f"Password: '{password1}' and Confirmation Password: '{password2}' do not match")
                    messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm
    return render (request=request, template_name="register.html", context={"register_form":form})

#Login

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, "You are now logged in")
				return redirect("Inventory:contenu")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="login.html", context={"login_form":form})


#Logout
def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.")
	return redirect("Inventory:index")


#signup
#class SignUp(CreateView):
    #form_class = forms.UserCreateForm
    #success_url = reverse_lazy("login")
    #template_name = "register.html"

#def

def display_Rocky_Railway(request):
    items = Product.objects.filter(Category=1)
    context = {
        'items' : items,
        'header' : 'Rocky_Railway'
    }

    return render(request,'contenu.html',context)

def display_Roar(request):
    items = Product.objects.filter(Category=2)
    context = {
        'items' : items,
        'header' : 'Roar'
    }

    return render(request,'contenu.html',context)

def display_Shipwreched(request):
    items = Product.objects.filter(Category=3)
    context = {
        'items' : items,
        'header' : 'Shipwreched'
    }

    return render(request,'contenu.html',context)

def display_FWN1(request):
    items = Product.objects.filter(Category=4)
    context = {
        'items' : items,
        'header' : 'FWN1'
    }

    return render(request,'contenu.html',context)

def display_FWN2(request):
    items = Product.objects.filter(Category=5)
    context = {
        'items' : items,
        'header' : 'FWN2'
    }

    return render(request,'contenu.html',context)

def display_FWN3(request):
    items = Product.objects.filter(Category=6)
    context = {
        'items' : items,
        'header' : 'FWN3'
    }

    return render(request,'contenu.html',context)

def display_LIFE_OF_JESUS(request):
    items = Product.objects.filter(Category=7)
    context = {
        'items' : items,
        'header' : 'LIFE_OF_JESUS'
    }

    return render(request,'contenu.html',context)


def display_Friends_with_God_Bible_Story(request):
    items = Product.objects.filter(Category=10)
    context = {
        'items' : items,
        'header' : 'Friends_with_God_Bible_Story'
    }

    return render(request,'contenu.html',context)


#adding
def add_device(request, cls):
    if request.method == "POST":
        form = cls(request.POST)

        if form.is_valid():
            form.save()
            return redirect('Inventory:contenu')
    else:
        form = cls()
        return render(request,'add_new.html', {'form':form})


def add_Rocky_Railway(request):
        return add_device(request, ProductForm)

def add_Roar(request):
        return add_device(request, ProductForm)

def add_Shipwreched(request):
        return add_device(request, ShipwrechedForm)

def add_FWN1(request):
        return add_device(request, FWN1Form)

def add_FWN2(request):
        return add_device(request, FWN2Form)

def add_FWN3(request):
        return add_device(request, FWN3Form)

def add_LIFE_OF_JESUS(request):
        return add_device(request, LIFE_OF_JESUSForm)

def add_Friends_with_God_Bible_Story(request):
        return add_device(request, Friends_with_God_Bible_StoryForm)


#editing
def edit_Rocky_Railway(request, pk):
    item = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        form = ProductForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('Inventory:contenu')

    else:
        form = ProductForm(instance=item)

        return render(request,'edit_item.html', {'form':form})

def edit_Roar(request, pk):
    item = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        form = ProductForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('Inventory:contenu')

    else:
        form = ProductForm(instance=item)

        return render(request,'edit_item.html', {'form':form})

def edit_Shipwreched(request, pk):
    item = get_object_or_404(Product, pk=pk)

    if request.method == "POST":

Inventory/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Inventory</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <style>
    /* Style the footer */
    footer {
      position: fixed;
      background-color: #3C8DBC;
      padding: 38px;
      text-align: center;
      bottom: 0;
      left: 0;
      right: 0;
      width: 100%;
      color: #FFFF;
            }

    .header {
      position: fixed;
      top:0;
      background-color: #3C8DBC;
      padding: 43px;
      width: 100%;
      }
    </style>
  </head>

  <body>
    <div class="header">
      <div class="container-fluid">
          <div class="row">
              <div class="col-lg-8"><strong><a class="navbar-brand " href="{% url 'Inventory:index' %}" style="color:#FFFF">GROUP PUBLISHING INDIA INVENTORY MANAGEMENT</a></strong></div>
              <div class="col-lg-4 text-right">

              <ul class="navbar-nav mr-auto navbar-fixed-top">
              {% if user.is_authenticated %}

              <li class="nav-item">
              <a href="#">Hi, Welcome {{ user.username }} | </a>
              <a href="{% url 'Inventory:logout' %}">Logout </a>
              </li>
              {% else %}
              <li class="nav-item">
              <a  class="rleo" href="{% url 'Inventory:login' %}">LogIn | </a>
              <a  class="rleo" href="{% url 'Inventory:register' %}">SignUp</a>
              </li>
              {% endif %}
              </ul>
              </div>
          </div>
     </div>
  </div>

    {% include "Inventory/partials/messages.html" %}

    <div >
      {% block body %}
      {% endblock %}
    </div>
    <footer>
      <strong><p style="font-size: 19px;">#12,2nd Cross BDS Gardens, Geddalahalli, Kothanur Post, Bangalore - 560077 | Contact: 080-28444099</p></strong>
      <strong><p style="font-size: 19px;">WWW.GROUPPUBLISHING.IN</p></strong>
    </footer>
  </body>
</html>

Inventory/templates/contenu.html
{% extends "base.html" %}
{% block body %}
<br>
<div class="jumbotron text-center" style="margin-top:100px">

    <a href="{% url 'Inventory:display_Rocky_Railway' %}" class="btn btn-primary btn-md" role="button" style="padding:10px 20px; font-size:20px; font:Adobe Garamond Pro Bold">ROCKY RAILWAY</a>

    <a href="{% url 'Inventory:display_Roar' %}" class="btn btn-primary btn-md" role="button" style="padding:10px 20px; font-size:20px; font:Adobe Garamond Pro Bold">ROAR</a>

    <a href="{% url 'Inventory:display_Shipwreched' %}" class="btn btn-primary btn-md" role="button" style="padding:10px 20px; font-size:20px; font:Adobe Garamond Pro Bold">SHIPWRECKED</a>

    <a href="{% url 'Inventory:display_FWN1' %}" class="btn btn-primary btn-md" role="button" style="padding:10px 20px; font-size:20px; font:Adobe Garamond Pro Bold">FWN1</a>

    <a href="{% url 'Inventory:display_FWN2' %}" class="btn btn-primary btn-md" role="button" style="padding:10px 20px; font-size:20px; font:Adobe Garamond Pro Bold">FWN2</a>

    <a href="{% url 'Inventory:display_FWN3' %}" class="btn btn-primary btn-md" role="button" style="padding:10px 20px; font-size:20px; font:Adobe Garamond Pro Bold">FWN3</a>

    <a href="{% url 'Inventory:display_LIFE_OF_JESUS' %}" class="btn btn-primary btn-md" role="button" style="padding:10px 20px; font-size:20px; font:Adobe Garamond Pro Bold">LIFE OF JESUS</a>

    <a href="{% url 'Inventory:display_Friends_with_God_Bible_Story' %}" class="btn btn-primary btn-md" role="button" style="padding:10px 20px; font-size:20px; font:Adobe Garamond Pro Bold">FRIENDS WITH GOD BIBLE STORY</a>
    <a href="{% url 'Inventory:add_Rocky_Railway' %}" class="btn btn-warning btn-sm" role="button" style="padding:4px 20px; font-size:30px; font:Adobe Garamond Pro Bold">+</a>

  <br>
  <br>
    <h6 style="font:Adobe Garamond Pro Bold">Currently Viewing {{header}}</h6>
  <br>

    <table class="table table-blue text-center">
    <thead>
        <tr>
          <th>ID</th>
          <th>PRODUCT</th>
          <th>TOTAL PRODUCED</th>
          <th>SALES</th>
          <th>TOTAL AVAILABLE</th>
        </tr>
    </thead>
    <tbody>

      {% for item in items %}
        <tr>
          <td style="font:Adobe Garamond Pro Bold">{{ item.pk }}</td>
          <td>{{ item.Product }}</td>
          <td>{{ item.Total_Produced }}</td>
          <td>{{ item.Sales }}</td>
          <td>{{ item.Save }}</td>

          {% if header == "Rocky_Railway" %}
          <td>
            <a href="{% url 'Inventory:edit_Rocky_Railway' item.pk %}" class="btn btn-warning btn-sm" role="button">Edit</a>
            <a href="{% url 'Inventory:delete_Rocky_Railway' item.pk %}" class="btn btn-danger btn-sm" role="button">X</a>
          </td>

          {% elif header == "Roar" %}
          <td>
            <a href="{% url 'Inventory:edit_Roar' item.pk %}" class="btn btn-warning btn-sm" role="button">Edit</a>
            <a href="{% url 'Inventory:delete_Roar' item.pk %}" class="btn btn-danger btn-sm" role="button">X</a>
          </td>

          {% elif header == "Shipwreched" %}
          <td>
            <a href="{% url 'Inventory:edit_Shipwreched' item.pk %}" class="btn btn-warning btn-sm" role="button">Edit</a>
            <a href="{% url 'Inventory:delete_Shipwreched' item.pk %}" class="btn btn-danger btn-sm" role="button">X</a>
          </td>

          {% elif header == "FWN1" %}
          <td>
            <a href="{% url 'Inventory:edit_FWN1' item.pk %}" class="btn btn-warning btn-sm" role="button">Edit</a>
            <a href="{% url 'Inventory:delete_FWN1' item.pk %}" class="btn btn-danger btn-sm" role="button">X</a>
          </td>

          {% elif header == "FWN2" %}
          <td>
            <a href="{% url 'Inventory:edit_FWN2' item.pk %}" class="btn btn-warning btn-sm" role="button">Edit</a>
            <a href="{% url 'Inventory:delete_FWN2' item.pk %}" class="btn btn-danger btn-sm" role="button">X</a>
          </td>

          {% elif header == "FWN3" %}
          <td>
            <a href="{% url 'Inventory:edit_FWN3' item.pk %}" class="btn btn-warning btn-sm" role="button">Edit</a>
            <a href="{% url 'Inventory:delete_FWN3' item.pk %}" class="btn btn-danger btn-sm" role="button">X</a>
          </td>

          {% elif header == "LIFE_OF_JESUS" %}
          <td>
            <a href="{% url 'Inventory:edit_LIFE_OF_JESUS' item.pk %}" class="btn btn-warning btn-sm" role="button">Edit</a>
            <a href="{% url 'Inventory:delete_LIFE_OF_JESUS' item.pk %}" class="btn btn-danger btn-sm" role="button">X</a>
          </td>

          {% else %}
          <td>
            <a href="{% url 'Inventory:edit_Friends_with_God_Bible_Story' item.pk %}" class="btn btn-warning btn-sm" role="button">Edit</a>
            <a href="{% url 'Inventory:delete_Friends_with_God_Bible_Story' item.pk %}" class="btn btn-danger btn-sm" role="button">X</a>
          </td>
          {% endif %}
      {% endfor %}

    </tbody>
  </table>
</div>
{% endblock %}

Inventory/templates/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}



<p>Total number registered: {{ count }}</p>

<p>
  <div class="jumbotron" style=" margin:400px; height: 400px 400px">
    <h1><strong><p  style="text-align:center;" >WELCOME TO GROUP PUBLISHING INDIA INVENTORY</p></strong></h1>
  </div>
</p>


{% endblock %}

Inventory/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
<!--Login-->

<div style="display:flex; justify-content:center; align-items:center">
<div class="container py-5" style="margin-top:230px; align:Center">
  <div class="jumbotron" style="align:Center">
  <h1>Login</h1>
  <br>
  <br>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}<br>
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <br>
  <p class="text-center">Don't have an account? <a href="{% url 'Inventory:register' %}">Create an account | </a>
  <a href="{% url 'reset_password' %}">Forgot your password.</a>
  </p>
  </div>
</div>
</div>
{% endblock %}

Inventory/templates/password_reset_complete.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}
<!--Password Reset Complete-->
  <div class="container p-5" style="display:flex; justify-content:center; align-items:center">
    <div class="jumbotron">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		    <hr>
        <p>Your password has been set. You may go ahead and log in now.</p>
        <a href="{% url 'Inventory:login' %}" class="btn btn-primary">Log in</a>
    </div>
  </div>
{% endblock %}

Inventory/templates/register.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
<!--Register-->



<div class="container py-5" style=" align:Center; padding-top:400px">
	<div class="jumbotron" style="align:Center; margin-top: 110px">
	<h1>Register</h1>
	<br>

	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}<br>
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'Inventory:login' %}">Login</a> instead.</p>
	</div>
</div>
{% endblock %}